FROM php:8.0-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid


# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    fish \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libpq-dev \
    libzip-dev \
    unzip

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
# Install PHP extensions
RUN docker-php-ext-install pdo_pgsql iconv gd zip opcache intl


# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# install xdebug
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug


# Set working directory
WORKDIR /app

USER $user
