version: "3.7"
services:

    transportir-php-fpm:
      container_name: tr-php-fpm
      build:
        args:
          user: user
          uid: 1000
        context: ./php
      working_dir: /app
      volumes:
        - ./../:/app
        - ./php/php-fpm-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
